on:
  push:
  workflow_dispatch:

name: Laravel-test

jobs:
  phpunit:
    runs-on: ubuntu-22.04
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3
    services:
      mysql:
        image: mysql:8.0.30
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts


      - name: Fake the vite-manifest
        run : |
          mkdir -p public/build/assets
          cp manifest.test.json public/build/manifest.json

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
